### ISSUE TITLE
How to use the new ack listener??

### ISSUE THREAD

**Issue by ManjitPardeshi** [open-wa/wa-automate-python#39]
@mrodal Please help me in using the new_acks listener....

**Comment by mrodal** [comment]
Hey @ManjitPardeshi, looks like its broken now, Im working on fixing it, and should be ready in a bit, here's an example of how to use it:

```python
class NewMessageObserver:
    def on_ack_received(self, ev):
        print(ev)


observer = NewMessageObserver()

driver.subscribe_acks(observer)

```

Inside `on_ack_received`, ev is a list of all the new acks, which are objects with the ack code, the chat id, the message, etc:
![image](https://user-images.githubusercontent.com/20667544/90189423-8df81c00-dd93-11ea-9754-673993789e8e.png)

The ack code can be 
1: Sent
2: Received
3: Read

**Comment by mrodal** [comment]
Please try with the latest version, 1.3.5

**Comment by ManjitPardeshi** [comment]
Thank you very much sir for your extremely fast reply.

**Comment by ManjitPardeshi** [comment]
@mrodal Eagerly looking for update

**Comment by mrodal** [comment]
I had published the new version to pypi, but maybe you use it directly from the repo. I have now pushed the changes to master

**Comment by ManjitPardeshi** [comment]
@mrodal sir thanks for fixing the issue this fast... closing...

**Comment by erm3nda** [comment]
You forgot the ack 4 for ptt messages, wich indicates "voice message has been listened".
